### ISSUE TITLE
Library cannot be imported in python3

### ISSUE THREAD

**Issue by Nerdietony** [rkuykendall/marvelous#2]
When i `pip3 import marvelous`

and try to import, it says the module doesn't exist

```
>>> import marvelous
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named marvelous

```

**Comment by rkuykendall** [comment]
Hey @Nerdietony, thanks for making this issue. I had no problem with `pip3 install marvelous`, but importing did uncover some issues with newer versions of python3. I'll work on issuing a fix for this tonight.

```bash
~ ⚡  pip3 install marvelous
Collecting marvelous
  Downloading marvelous-0.0.4.tar.gz
Collecting marshmallow (from marvelous)
  Downloading marshmallow-2.10.3-py2.py3-none-any.whl (44kB)
    100% |████████████████████████████████| 51kB 3.6MB/s 
Collecting requests (from marvelous)
  Downloading requests-2.11.1-py2.py3-none-any.whl (514kB)
    100% |████████████████████████████████| 522kB 1.5MB/s 
Building wheels for collected packages: marvelous
  Running setup.py bdist_wheel for marvelous ... done
  Stored in directory: /Users/rkuykendall/Library/Caches/pip/wheels/fb/c1/df/d784fb26a839974c748eb45e9bfb3470b9dfc30910c13267c4
Successfully built marvelous
Installing collected packages: marshmallow, requests, marvelous
Successfully installed marshmallow-2.10.3 marvelous-0.0.4 requests-2.11.1
~ ⚡  python3
Python 3.5.2 (default, Aug  5 2016, 15:23:33) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import marvelous
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/marvelous/__init__.py", line 1, in <module>
    from session import Session
ImportError: No module named 'session'
```

**Comment by rkuykendall** [comment]
Just an update: I was not able to get it up and running that night, but I will have plenty of time this weekend to work on it.

**Comment by rkuykendall** [comment]
@Nerdietony The new release, marvelous 1.0.0, is now 100% python 3 compatible. I actually dropped support of python 2 in favor of it. Just run `pip3 install marvelous --upgrade` and everything should work.
